%% Script_02_ProcessMPPMatrix
% Specify inputs
path_MPPMatrix = ''; % specify path to the .mat file generated in Script_01 (called path_save_raw) which contains MPP related variables, e.g. path_save_raw
stains_to_exclude = []; % specify which 4i channels should be excluded from further analysis
val_background = []; % specify background intensity value of the camera chip  e.g. 110
val_quantile = []; % specify quantile value, which should be used to rescale intensties of each 4i channel between 0 and 100, where val_quantile will be 100, e.g. 0.98
val_threshold = []; % specify which singal value should be used to exclude MPP profile, if all 4i channel intensities lay below val_threshold, e.g. 33.333333333
name_output = ''; % specify a name, with which you want to label all outputs, e.g. use same name as used in Script_01
path_output = ''; % specify directory, where all outputs should be saved, e.g. use same path as used in Script_01

% Run process_MPPMatrix_MPPmetadata function. It will generate a cleaned up version of MMP Matrix and MPP metadata according to the specifications provided.
[mpp_matrix, mpp_metadata, cells_metadata, path_save_processed] = process_MPPMatrix_MPPmetadata(    path_MPPMatrix,...
                                                                                                    stains_to_exclude,...
                                                                                                    val_background,...
                                                                                                    val_quantile,...
                                                                                                    val_threshold,...
                                                                                                    name_output,...
                                                                                                    path_output);