%% Script_01_GenerateMPPMatrix
% Specify inputs
path_project = ''; % specify path to project, see supporting pdf for expected directory structure
str_sharedfoldername = ''; % specify string which is present in all folders of the individual cycles
path_cellmetadata_info = ''; % specify path to metadata of cells, from which a Multiplexed Protein Map should be built
sites_per_well = []; % number of microscopy sites acquired per well, e.g. 42
str_seg_object = ''; % specify the segmetation object, which you want to use as a mask to extract multiplexed pixel profiles, e.g. Cells
channel_dapi = []; % Specify digit which specifies DAPI signal of your 4i cycle in your filenames e.g. 1 for "Images_C03_T0001F001A01Z01C01.png"
channel_green = []; % Specify digit which specifies second signal of your 4i cycle (often green) in your filenames e.g. 2 for "Images_C03_T0001F001A01Z01C02.png"
channel_red = []; % Specify digit which specifies third signal of your 4i cycle (often green) in your filenames e.g. 3 for "Images_C03_T0001F001A01Z01C03.png"
num_parallel = []; % specify number of parallelizations you want, e.g. 8
name_output = ''; % specify a name, with which you want to label all outputs, e.g. Test
path_output = ''; % specify directory, where all outputs should be saved

% Run extract_MPPMatrix function. It will generate MMP Matrix of num_cells specified randomly selected cells and save MPP Matrix specified directory
% extract_MPPMatrix will extract DAPI signal (channel_dapi) only for the first cycle.
path_output = fullfile(path_output, 'MatlabOutput');
[mpp_matrix, mpp_metadata, cells_metadata, list_channel, path_save_raw] = extract_MPPMatrix(    path_project,...    
                                                                                                str_sharedfoldername,...
                                                                                                path_cellmetadata_info,...
                                                                                                sites_per_well,...
                                                                                                str_seg_object,...
                                                                                                channel_dapi,...
                                                                                                channel_green,...
                                                                                                channel_red,...
                                                                                                num_parallel,...
                                                                                                name_output,...
                                                                                                path_output)